server:
  port: 8080

spring:
  application:
    name: moongkl-here-mobile-api

  h2:
    console:
      enabled: true
      path: /h2-console
    datasource:
      url: jdbc:h2:mem:testdb
      username: sa
      password: sa
      driver-class-name: org.h2.Driver

  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul
        show_sql: true
        format_sql: true
    repositories:
      enabled: true

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    s3:
      bucket: files.mobile-api.moongkl.com
      root-directory: ${AWS_S3_ROOT_DIRECTORY}
      skin-directory: skin
      story-directory: story

    region:
      static: ap-northeast-2
    stack:
      auto: false
    cloudfront:
      distribution-domain: ${CLOUDFRONT_URL}