server:
  port: 8080

spring:
  servlet:
    multipart:
      resolve-lazily: true
      max-file-size: 50MB
      max-request-size: 100MB
  application:
    name: moongkl-here-mobile-api
  datasource:
    url: jdbc:mariadb://${MARIA_HOST}:${MARIA_PORT}/${INITIAL_DB}?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ${MARIA_USERNAME}
    password: ${MARIA_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
      schema-locations:
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: false
    hibernate:
      ddl-auto: ${SPRING_DATASOURCE_DDL_AUTO}
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul
        show_sql: false
        format_sql: true
    repositories:
      enabled: true
    defer-datasource-initialization: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  security:
    oauth2:
      redirect-uri: ${SUCCESS_REDIRECT_URI}
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${OAUTH2_BASE_URI}/oauth2/callback/google
            scope: email
            authorization-grant-type: authorization_code
          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            redirect-uri: ${OAUTH2_BASE_URI}/oauth2/callback/naver
            authorization-grant-type: authorization_code
            scope: email
            client-name: naver
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: ${OAUTH2_BASE_URI}/oauth2/callback/kakao
            client-authentication-method: POST
            scope: account_email
            authorization-grant-type: authorization_code
          facebook:
            client-id: ${FACEBOOK_CLIENT_ID}
            client-secret: ${FACEBOOK_CLIENT_SECRET}
            redirect-uri: ${OAUTH2_BASE_URI}/oauth2/callback/facebook
            authorization-grant-type: authorization_code
            scope: email
            client-name: facebook
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

naver-cloud-sms:
  accessKey: ${SMS_ACCESS_KEY}
  secretKey: ${SMS_SECRET_KEY}
  serviceId: ${SMS_SERVICE_ID}
  senderPhoneNumber: ${SMS_SENDER_NUMBER}

app:
  jwt:
    secret: ${APP_JWT_SECRET}
    expiration: ${APP_JWT_EXPIRATION}

springfox:
  documentation:
    swagger-ui:
      enabled: true
cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    s3:
      bucket: moongklhere-files
      root-directory: ${AWS_S3_ROOT_DIRECTORY}
      skin-directory: skin
      story-directory: story
      profile-directory: profile
      background-directory: background
    region:
      static: ap-northeast-2
    stack:
      auto: false
    cloudfront:
      distribution-domain: ${CLOUDFRONT_URL}
    sqs:
      queue-url: ${AWS_SQS_QUEUE_URL}
      #queue-url: ${LOCAL_SQS_QUEUE_URL}
      queue-name: ${AWS_SQS_QUEUE_NAME} # listen
      #queue-name: ${LOCAL_SQS_QUEUE_NAME} # listen
      handler:
        default-deletion-policy: ON_SUCCESS
  gcp:
   geo-coding:
     api-key: ${GCP_GEOCODING_API_KEY}

services:
  geo-coding-service: https://maps.googleapis.com/maps/api/geocode
  place-autocomplete-service: https://maps.googleapis.com/maps/api/place/autocomplete

converter:
  secret-key: ${CONVERTER_SECRET_KEY}

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
