springfox:
  documentation:
    swagger-ui:
      enabled: true


naver-cloud-sms:
  accessKey: SQ1muTDWpHGnKnD5Nol2
  secretKey: WhzmxqVPsalYPlWtdUTjnDA0jjEGTDvjDgz3K2gD
  serviceId: ncp:sms:kr:317088518686:sms_mh
  senderPhoneNumber: 01077248375